OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
WPM_ENABLE= yes
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = yes     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE = yes
LTO_ENABLE = yes
#SERIAL_DRIVER = uart
#OS_DETECTION_ENABLE = yes
#AVR_USE_MINIMAL_PRINTF = yes
#SPLIT_KEYBOARD = yes
#SPLIT_USB_TIMEOUT = 100
#SPLIT_TRANSPORT = serial
#SPLIT_TRANSPORT_SYNC_ENABLE = yes
#SPLIT_TRANSACTION_ENABLE = yes 
#TRANSACTION_ENABLE = yes
#SPLIT_KEYBOARD = yes
#SPLIT_TRANSPORT = serial